# Módulo `statistics`

In [5]:
import statistics as stats

In [2]:
dir(statistics)

['Counter',
 'Decimal',
 'Fraction',
 'LinearRegression',
 'NormalDist',
 'StatisticsError',
 '_SQRT2',
 '__all__',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_decimal_sqrt_of_frac',
 '_exact_ratio',
 '_fail_neg',
 '_float_sqrt_of_frac',
 '_integer_sqrt_of_frac_rto',
 '_isfinite',
 '_mean_stdev',
 '_normal_dist_inv_cdf',
 '_rank',
 '_sqrt_bit_width',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'correlation',
 'count',
 'covariance',
 'defaultdict',
 'erf',
 'exp',
 'fabs',
 'fmean',
 'fsum',
 'geometric_mean',
 'groupby',
 'harmonic_mean',
 'hypot',
 'itemgetter',
 'linear_regression',
 'log',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'multimode',
 'namedtuple',
 'numbers',
 'pstdev',
 'pvariance',
 'quantiles',
 'random',
 'reduce',
 'repeat',
 'sqrt',
 'stdev',
 'sumprod',
 'sys',
 'tau',
 'variance']

In [3]:
datos = [1, 2, 3, 4, 5]

In [6]:
stats.mean(datos)

3

In [7]:
stats.median(datos)

3

In [8]:
stats.stdev(datos)

1.5811388300841898

In [9]:
stats.variance(datos)

2.5

In [10]:
datos1=[2,3,5,2,4]

In [11]:
stats.covariance(datos,datos1)

0.75

## Numpy
Vea [numpy](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [14]:
%pip install numpy
import numpy as np

In [20]:
a = np.array([11, 2, 35, 45, 59, 6])
a

array([11,  2, 35, 45, 59,  6])

In [22]:
a.ndim

1

In [23]:
a.size

6

In [24]:
a.shape

(6,)

In [18]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b.shape

(3, 4)

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.sort(a)

array([ 2,  6, 11, 35, 45, 59])

In [34]:
b < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [35]:
b[b<6]

array([1, 2, 3, 4, 5])

In [15]:
%pip install scipy
import scipy as sp

Vea [Scipy](https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide)

In [36]:
import scipy.stats as stats

In [50]:
y = stats.expon.rvs(7, size=1000)

In [51]:
y.min()

np.float64(7.0015182262301705)

In [52]:
y.max()

np.float64(13.507599785751149)

In [53]:
y.mean()

np.float64(7.995986053671514)

In [54]:
y.var()

np.float64(0.926857951058388)

In [55]:
stats.describe(y)

DescribeResult(nobs=np.int64(1000), minmax=(np.float64(7.0015182262301705), np.float64(13.507599785751149)), mean=np.float64(7.995986053671514), variance=np.float64(0.9277857367951833), skewness=np.float64(1.6416590738783166), kurtosis=np.float64(3.44742271252941))

In [56]:
stats.gmean(y)

np.float64(7.9438160542211484)

In [60]:
stats.hmean(y)

np.float64(7.896635130151766)

In [57]:
stats.moment(y, moment=3)

np.float64(1.46488233304575)

In [61]:
stats.moment(y, moment=4)

np.float64(5.538759457123344)

In [58]:
stats.skew(y)

np.float64(1.6416590738783166)

In [59]:
stats.kurtosis(y)

np.float64(3.44742271252941)

In [67]:
stats.quantile(y, [0.25, 0.75])

array([7.2739796 , 8.44804525])

In [69]:
stats.percentileofscore(y, 8)

np.float64(64.2)