# Módulo `statistics`

In [4]:
import statistics as stats

In [5]:
dir('statistics')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [6]:
datos = [1, 2, 3, 4, 5]

In [7]:
stats.mean(datos)

3

In [8]:
stats.median(datos)

3

In [9]:
stats.stdev(datos)

1.5811388300841898

In [10]:
stats.variance(datos)

2.5

In [11]:
datos1=[2,3,5,2,4]

In [12]:
stats.covariance(datos,datos1)

0.75

## Numpy
Vea [numpy](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [13]:
%pip install numpy
import numpy as np

/Users/carloslesmes/Dropbox/COLAB/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.


In [14]:
a = np.array([11, 2, 35, 45, 59, 6])
a

array([11,  2, 35, 45, 59,  6])

In [15]:
a.ndim

1

In [16]:
a.size

6

In [17]:
a.shape

(6,)

In [18]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
b.shape

(3, 4)

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.sort(a)

array([ 2,  6, 11, 35, 45, 59])

In [24]:
b < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [25]:
b[b<6]

array([1, 2, 3, 4, 5])

In [26]:
%pip install scipy
import scipy as sp

/Users/carloslesmes/Dropbox/COLAB/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.


Vea [Scipy](https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide)

In [27]:
import scipy.stats as stats

In [28]:
y = stats.expon.rvs(7, size=1000)

In [29]:
y.min()

np.float64(7.000842068216547)

In [30]:
y.max()

np.float64(14.819009488885534)

In [31]:
y.mean()

np.float64(8.004593790070414)

In [32]:
y.var()

np.float64(0.9858998208008827)

In [33]:
stats.describe(y)

DescribeResult(nobs=np.int64(1000), minmax=(np.float64(7.000842068216547), np.float64(14.819009488885534)), mean=np.float64(8.004593790070414), variance=np.float64(0.9868867075083911), skewness=np.float64(1.6912440784357547), kurtosis=np.float64(3.706468576359039))

In [34]:
stats.gmean(y)

np.float64(7.949503954688505)

In [35]:
stats.hmean(y)

np.float64(7.8999977783270525)

In [36]:
stats.moment(y, moment=3)

np.float64(1.6556002012632889)

In [37]:
stats.moment(y, moment=4)

np.float64(6.518677105827666)

In [38]:
stats.skew(y)

np.float64(1.6912440784357547)

In [39]:
stats.kurtosis(y)

np.float64(3.706468576359039)

In [40]:
stats.quantile(y, [0.25, 0.75])

array([7.27987796, 8.40335132])

In [41]:
stats.percentileofscore(y, 8)

np.float64(63.0)